services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    volumes:
      - .:/app
    command: /bin/sh -c 'npm install && npm run dev'
    environment:
      - WATCHPACK_POLLING=true
