version: "3.9"

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3020:3000"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
